export interface Trade {
  accountId: number,
  depotId: number,
  name: string,
  symbol: string,
  quoteType: string,
  currency: string,
  buyPrice: number,
  buyPriceAll: number,
  entryPrice: number,
  entryPriceAll: number,
  amount: number,
  exitPrice: number,
  lastPrice: number,
  lastDate: Date,
  profitLoss: number,
  profitLossPercentage: number,
  exitPriceDefault: number,
  currencyDefault: string,
}

export interface TradeDiversification {
  id: number,
  name: string,
  symbol: string,
  quoteType: string,
  sector: string,
  industry: string,
  exitPrice: number,
  currency: string,
  exitPriceDefault: number,
  currencyDefault: string,
  realEstate: string,
  account: string,
  depot: string,
}
